spring.application.name=rentcity

# C?u hình k?t n?i MySQL (MAMP)
spring.datasource.url=jdbc:mysql://localhost:3306/rentcity_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# C?u hình Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# XÓA HO?C COMMENT DÒNG D??I ?ÂY:
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect