### Đặt xe mới
POST http://localhost:8080/api/bookings
Content-Type: application/json

{
  "vehicleId": "8f6ad81f-e019-4b0b-a7ff-3a6a4e48bb2e",
  "customerId": "KH001",
  "startDatetime": "2026-04-20T08:00:00",
  "endDatetime": "2026-04-22T20:00:00"
}