spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rent_city
    username: postgres
    password: 123456

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

server:
  port: 8080

jwt:
  secret: mysecretkey123